spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_prod}?useSSL=false&serverTimezone=UTC
#    username: ${DB_USER:root}
#    password: ${DB_PASS:password}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#  liquibase:
#    should-run: true
#    change-log: classpath:liquibase/db.changelog-prod.yml
#
#  sql:
#    init:
#      mode: never

server:
  port: 8000

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: ERROR
    liquibase: INFO
    org.springframework.jdbc.core: WARN
